/* model_arch.h — generated by train_persondetectionmodel.py (v6)
 * PersonNet-181 (12 layers) for archway_npu rev4 (Tier-1). DO NOT EDIT. */
#ifndef MODEL_ARCH_H
#define MODEL_ARCH_H
#include <stdint.h>

#define MODEL_NAME        "persondetectionmodel"
#define INPUT_W           181
#define INPUT_H           181
#define INPUT_CH          1
#define INPUT_BYTES       (INPUT_W*INPUT_H*INPUT_CH)
#define INPUT_SCALE       0.00784313725f  /* real = q * this */
#define NUM_LAYERS        12
#define WEIGHTS_TOTAL_BYTES 165192
#define LAST_ACC_SCALE    0.167304362f  /* head logit = int8 * this */
#define GRID              16
#define HEAD_CH           8
#define OUTPUT_BYTES      (GRID*GRID*HEAD_CH)
#define ANCHOR_W          0.183034193f
#define ANCHOR_H          0.268224962f
#define CONF_THRESH       0.95f  /* from tiled sweep */
#define NMS_IOU           0.45f
#define TILE_STRIDE       119   /* px, tiled scan default */
#define NUM_TILE_SCALES   3
#define TILE_SCALES       {1.2f, 0.5f, 0.2f}   /* MUST match trainer --tile-scales */
#define MIN_VOTES         2   /* tiled cross-scale agreement gate */
#define HIGH_CONF         0.85f  /* lone confident tile kept without a 2nd vote */
#define VOTE_FLOOR        0.2f  /* collect tiles down to this conf; CONF_THRESH applied AFTER the vote */

typedef struct {
    uint16_t in_ch, out_ch;
    uint16_t in_h, in_w, out_h, out_w;
    uint8_t  k, stride, pad, relu;
    uint32_t weight_offset;   /* bytes into weights.bin */
    uint32_t weight_count;    /* int8 values (OIHW)     */
    uint16_t qscale;
    uint8_t  qshift;
} layer_config_t;

static const layer_config_t model_layers[NUM_LAYERS] = {
    {1, 8, 181, 181, 61, 61, 3, 3, 1, 1, 0u, 72u, 40509, 23},  /* L1 */
    {8, 24, 61, 61, 31, 31, 3, 2, 1, 1, 72u, 1728u, 38178, 23},  /* L2 */
    {24, 32, 31, 31, 31, 31, 3, 1, 1, 1, 1800u, 6912u, 46069, 23},  /* L3 */
    {32, 32, 31, 31, 31, 31, 3, 1, 1, 1, 8712u, 9216u, 37297, 24},  /* L4 */
    {32, 48, 31, 31, 16, 16, 3, 2, 1, 1, 17928u, 13824u, 58802, 25},  /* L5 */
    {48, 56, 16, 16, 16, 16, 3, 1, 1, 1, 31752u, 24192u, 40114, 26},  /* L6 */
    {56, 56, 16, 16, 16, 16, 3, 1, 1, 1, 55944u, 28224u, 49972, 22},  /* L7 */
    {56, 56, 16, 16, 16, 16, 3, 1, 1, 1, 84168u, 28224u, 38221, 24},  /* L8 */
    {56, 56, 16, 16, 16, 16, 3, 1, 1, 1, 112392u, 28224u, 33853, 24},  /* L9 */
    {56, 128, 16, 16, 16, 16, 1, 1, 0, 1, 140616u, 7168u, 35138, 23},  /* L10 */
    {128, 128, 16, 16, 16, 16, 1, 1, 0, 1, 147784u, 16384u, 43424, 23},  /* L11 */
    {128, 8, 16, 16, 16, 16, 1, 1, 0, 0, 164168u, 1024u, 39322, 26},  /* L12 */
};

#endif /* MODEL_ARCH_H */
